<a href="https://colab.research.google.com/github/suryapratapkhuntia/Machine_learning_real_world_projects_for_practice/blob/main/indian_yield_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('/content/archive (22).zip')
df

State  ...     Yield
0       Andaman and Nicobar Islands  ...  1.643541
1       Andaman and Nicobar Islands  ...  1.655803
2       Andaman and Nicobar Islands  ...  1.209358
3       Andaman and Nicobar Islands  ...  1.690000
4       Andaman and Nicobar Islands  ...  1.696296
...                             ...  ...       ...
345402                      Manipur  ...       NaN
345403                      Manipur  ...       NaN
345404                      Manipur  ...       NaN
345405                      Manipur  ...       NaN
345406                      Manipur  ...       NaN

[345407 rows x 10 columns]

In [5]:
df.isnull().sum()

State                  0
District               0
Crop                  32
Year                   0
Season                 1
Area                  33
Area Units             0
Production          4993
Production Units       0
Yield                 33
dtype: int64

In [6]:
df_cleaned = df.dropna(subset=['Production'])
display(df_cleaned)

State  ...     Yield
0       Andaman and Nicobar Islands  ...  1.643541
1       Andaman and Nicobar Islands  ...  1.655803
2       Andaman and Nicobar Islands  ...  1.209358
3       Andaman and Nicobar Islands  ...  1.690000
4       Andaman and Nicobar Islands  ...  1.696296
...                             ...  ...       ...
345370                  West Bengal  ...  2.421553
345371                  West Bengal  ...  1.456464
345372                  West Bengal  ...  1.480193
345373                  West Bengal  ...  2.517442
345374                  West Bengal  ...  2.494126

[340414 rows x 10 columns]

In [7]:
df_cleaned.isnull().sum()

State               0
District            0
Crop                0
Year                0
Season              0
Area                0
Area Units          0
Production          0
Production Units    0
Yield               0
dtype: int64

In [8]:
df_cleaned['Area Units'].value_counts()

Area Units
Hectare    340414
Name: count, dtype: int64

In [9]:
df_cleaned['Production Units'].value_counts()

Production Units
Tonnes    326999
Bales      10524
Nuts        2891
Name: count, dtype: int64

In [10]:
df_cleaned['Season'].value_counts()

Season
Kharif        136165
Rabi           99805
Whole Year     67265
Summer         21974
Winter          8238
Autumn          6967
Name: count, dtype: int64

In [11]:
df_cleaned['Crop'].value_counts()

Crop
Rice                     21573
Maize                    20329
Moong(Green Gram)        14813
Urad                     14389
Sesamum                  12744
Groundnut                12515
Wheat                    11219
Rapeseed &Mustard        10919
Sugarcane                10826
Arhar/Tur                10774
Potato                   10729
Onion                    10621
Gram                     10330
Jowar                     9682
Dry chillies              8890
Bajra                     7740
Peas & beans (Pulses)     7179
Sunflower                 7104
Small millets             6859
Cotton(lint)              6318
Masoor                    6296
Turmeric                  5916
Barley                    5808
Linseed                   5793
Ragi                      5725
Sweet potato              5656
Other Kharif pulses       5590
Horse-gram                5294
Garlic                    4958
Coriander                 4954
Soyabean                  4953
Other Rabi pulses         4728
Ginger                    4652
Castor seed               4496
Banana                    4393
Tobacco                   3513
Coconut                   2891
Sannhamp                  2738
Niger seed                2707
Mesta                     2369
Tapioca                   2264
Arecanut                  2150
Guar seed                 2045
Jute                      1837
Khesari                   1753
Safflower                 1727
Cowpea(Lobia)             1697
Cashewnut                 1519
Black pepper              1370
Other Cereals             1338
Moth                      1287
other oilseeds            1190
Oilseeds total             702
Cardamom                   483
Other Summer Pulses         66
Dry Ginger                   3
Name: count, dtype: int64

In [12]:
df_cleaned.duplicated().sum()

np.int64(0)

In [13]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler

In [14]:
df_cleaned.describe()

Area    Production          Yield
count  3.404140e+05  3.404140e+05  340414.000000
mean   1.182535e+04  9.583711e+05      80.564577
std    4.612484e+04  2.152986e+07     923.232000
min    8.000000e-03  0.000000e+00       0.000000
25%    8.000000e+01  8.700000e+01       0.567920
50%    5.630000e+02  7.170000e+02       1.025000
75%    4.257000e+03  7.176000e+03       2.500000
max    8.580100e+06  1.597800e+09   43958.333333

In [15]:
std_col=df_cleaned[['Area','Production','Yield']]
onehe_col =df_cleaned[['Crop','State','District']]
ordinar_col=df_cleaned[['Season','Production Units']]

In [16]:
std=StandardScaler()
std_col_scaled=std.fit_transform(std_col)
std_col_scaled

array([[-0.22919022, -0.04441793, -0.08548355],
       [-0.2291035 , -0.04441691, -0.08547027],
       [-0.22903846, -0.04444282, -0.08595384],
       ...,
       [-0.17537965, -0.0442568 , -0.08566048],
       [-0.19671309, -0.04419187, -0.08453698],
       [-0.19179166, -0.04416855, -0.08456224]])

In [17]:
ohe=OneHotEncoder()
onehe_col_encoded=ohe.fit_transform(onehe_col).toarray()
onehe_col_encoded

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
ordinal=OrdinalEncoder()
ordinar_col_encoded=ordinal.fit_transform(ordinar_col)
ordinar_col_encoded

array([[1., 2.],
       [4., 2.],
       [4., 2.],
       ...,
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [19]:


std_col=df_cleaned[['Area','Production']]
onehe_col =df_cleaned[['Crop','State','District']]
ordinar_col=df_cleaned[['Season','Production Units']]

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), std_col.columns),
        ('cat_ohe', OneHotEncoder(handle_unknown='ignore'), onehe_col.columns),
        ('cat_ord', OrdinalEncoder(), ordinar_col.columns)
    ],
    remainder='drop'
)

df_processed = preprocessor.fit_transform(df_cleaned)
display(df_processed)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2365407 stored elements and shape (340414, 824)>

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import  r2_score

In [21]:
x_train,x_test,y_train,y_test=train_test_split(df_processed,df_cleaned['Yield'],test_size=0.2,random_state=42)

In [22]:
lin_reg=LinearRegression()
lin_reg.fit(x_train,y_train)

LinearRegression()

In [23]:
y_pred=lin_reg.predict(x_test)
r2_score(y_test,y_pred)

0.8039506176798773

In [24]:
from sklearn.tree import DecisionTreeRegressor

In [25]:
dt_reg=DecisionTreeRegressor()
dt_reg.fit(x_train,y_train)

DecisionTreeRegressor()

In [26]:
y_pred=dt_reg.predict(x_test)
r2_score(y_test,y_pred)

0.9603571530993952